/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment1;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Library{
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
